import calculus_functions_infinite_dimensional_spaces_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace calculus_functions_infinite_dimensional_spaces_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end calculus_functions_infinite_dimensional_spaces_theorem_canonical_lane_mathlib
end HautevilleHouse
